// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/wexinc/ps-tag-onboarding-go/internal/model"

	utils "github.com/wexinc/ps-tag-onboarding-go/internal/utils"
)

// IUserService is an autogenerated mock type for the IUserService type
type IUserService struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: id
func (_m *IUserService) DeleteUser(id int64) utils.MessageErr {
	ret := _m.Called(id)

	var r0 utils.MessageErr
	if rf, ok := ret.Get(0).(func(int64) utils.MessageErr); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(utils.MessageErr)
		}
	}

	return r0
}

// GetAllUsers provides a mock function with given fields:
func (_m *IUserService) GetAllUsers() ([]model.User, utils.MessageErr) {
	ret := _m.Called()

	var r0 []model.User
	var r1 utils.MessageErr
	if rf, ok := ret.Get(0).(func() ([]model.User, utils.MessageErr)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}

	if rf, ok := ret.Get(1).(func() utils.MessageErr); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(utils.MessageErr)
		}
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: id
func (_m *IUserService) GetUser(id int64) (*model.User, utils.MessageErr) {
	ret := _m.Called(id)

	var r0 *model.User
	var r1 utils.MessageErr
	if rf, ok := ret.Get(0).(func(int64) (*model.User, utils.MessageErr)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *model.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) utils.MessageErr); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(utils.MessageErr)
		}
	}

	return r0, r1
}

// SaveUser provides a mock function with given fields: user
func (_m *IUserService) SaveUser(user *model.User) (*model.User, utils.MessageErr) {
	ret := _m.Called(user)

	var r0 *model.User
	var r1 utils.MessageErr
	if rf, ok := ret.Get(0).(func(*model.User) (*model.User, utils.MessageErr)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*model.User) *model.User); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.User) utils.MessageErr); ok {
		r1 = rf(user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(utils.MessageErr)
		}
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: user
func (_m *IUserService) UpdateUser(user *model.User) (*model.User, utils.MessageErr) {
	ret := _m.Called(user)

	var r0 *model.User
	var r1 utils.MessageErr
	if rf, ok := ret.Get(0).(func(*model.User) (*model.User, utils.MessageErr)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*model.User) *model.User); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.User) utils.MessageErr); ok {
		r1 = rf(user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(utils.MessageErr)
		}
	}

	return r0, r1
}

// NewIUserService creates a new instance of IUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserService {
	mock := &IUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
