version: "3.3"

services:
  ps-tag-onboarding-go:
    image: wexinc/ps-tag-onboarding-go:latest
    container_name: ps-tag-onboarding-go
#    build: .
    restart: unless-stopped
    ports:
      - 8089:8089
    environment:
      - HTTP_PORT=8089