version: "3.3"

services:
  ps-tag-onboarding-go:
    image: wexinc/ps-tag-onboarding-go:latest
    container_name: ps-tag-onboarding-go
#    build: .
    restart: unless-stopped
    ports:
      - 8089:8089
    environment:
      - HTTP_PORT=8089
#      - HTTP_PORT=${HTTP_PORT}
#      - JWT_SIGN_KEY=${JWT_SIGN_KEY}
#      - JWT_VERIFY_KEY=${JWT_VERIFY_KEY}
#      - DB_USER=${DB_USER}
#      - DB_NAME=${DB_NAME}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_TZ=${DB_TZ}
#      - DB_SSL_MODE=${DB_SSL_MODE}
#    ports:
##      - ${HTTP_PORT}:${HTTP_PORT}
#      - 8089:8089