// Code generated by go-swagger; DO NOT EDIT.

// Package restapi provides a simple API server.
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /users/
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
