basePath: /users/
consumes:
    - application/json
definitions:
    MessageErr:
        properties:
            Error:
                type: string
            Message:
                type: string
            Status:
                format: int64
                type: integer
        title: MessageErr represents a error message.
        type: object
        x-go-package: github.com/wexinc/ps-tag-onboarding-go/internal/utils
    User:
        properties:
            age:
                format: int64
                type: integer
                x-go-name: Age
            email:
                type: string
                x-go-name: Email
            first_name:
                type: string
                x-go-name: FirstName
            id:
                format: int64
                type: integer
                x-go-name: Id
            last_name:
                type: string
                x-go-name: LastName
        title: User represents a user.
        type: object
        x-go-package: github.com/wexinc/ps-tag-onboarding-go/internal/model
host: localhost
info:
    title: provides a simple API server.
    version: 1.0.0
paths:
    /users:
        post:
            consumes:
                - application/json
            operationId: createUser
            produces:
                - application/json
            responses:
                "201":
                    description: User
                    schema:
                        $ref: '#/definitions/User'
                "400":
                    description: MessageErr
                    schema:
                        $ref: '#/definitions/MessageErr'
                "500":
                    description: MessageErr
                    schema:
                        $ref: '#/definitions/MessageErr'
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
